version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project
permissions:
  - object: /home/ubuntu/project
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: /home/ubuntu/project/scripts/deploy.sh
      timeout: 300
      runas: ubuntu
