version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /home/ubuntu/project
    owner: root
    group: ubuntu
hooks:
  BeforeInstall:
    - location: /home/ubuntu/project/scripts/deploy.sh
      timeout: 300
      runas: root
