version: 0.2

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - python manage.py test
      - python manage.py collectstatic --noinput
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    - '!**/staticfiles/**'