# Generated by Django 4.1.7 on 2023-02-28 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('expiry', models.DateTimeField()),
                ('otp_type', models.CharField(choices=[('VERIFY_MOBILE', 'VERIFY_MOBILE'), ('VERIFY_EMAIL', 'VERIFY_EMAIL'), ('LOGIN_OTP', 'LOGIN_OTP'), ('FORGET_PASSWORD', 'FORGET_PASSWORD')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Based OTP',
            },
        ),
    ]
